name: Shell Commands
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a strinng
        run: echo "oh hello"
      - name: multiline scripting yo
        run: |
          node -v
          npm -v