name: Shell Commands
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Copy In Repo
        uses: actions/checkout@v1
      - name: List Files after copy
        run: |
          pwd
          ls -a
          $GITHUB_SHA
          $GITHUB_REPOSITORY
          $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: echo a strinng
        run: echo "oh hello"
      - name: multiline scripting yo
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
        